package Course.Managment.System;

import Course.Managment.System.AdminPage;
import Course.Managment.System.StudentWork;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author rajas
 */


public class ViewStudentDetails extends javax.swing.JFrame {
    Student s= new Student();
    
    public ViewStudentDetails() {
        initComponents();
        String fetch_user;
        AdminPage a = new AdminPage();
        fetch_user = a.getUserNameofStudents();
        s.setUserName(fetch_user);
        
//          fetch_user="student";
        try{
            
            s.showDetails();
            
            if(s.x)
            {
                Name.setText(s.getUserName());
                FirstnameHolder.setText(s.getFirstName());
                LastNameHolder.setText(s.getLastName());
                DOBHolder.setText(s.getDob());
                ContactHolder.setText(s.getContact());
                StreamHolder.setText(s.getStream());
                SemesterHolder.setText(s.getSemester());
                BloodGroupHolder.setText(s.getBloodGroup());
                Addressholder.setText(s.getAddress());
                passwordHolder.setText(s.getPassword());
            }
            else
            {
                JOptionPane.showMessageDialog(this,"No Record found!");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstnameHolder = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LastNameHolder = new javax.swing.JTextField();
        DOBHolder = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ContactHolder = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        BloodGroupHolder = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Addressholder = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        passwordHolder = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        StreamHolder = new javax.swing.JLabel();
        SemesterHolder = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FirstnameHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameHolderActionPerformed(evt);
            }
        });
        getContentPane().add(FirstnameHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 129, 119, -1));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 527, -1));

        jLabel2.setText("UserName");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, 78, 19));

        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, 67, -1));

        LastNameHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameHolderActionPerformed(evt);
            }
        });
        getContentPane().add(LastNameHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 129, 131, -1));
        getContentPane().add(DOBHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 166, 119, -1));

        jLabel4.setText("Date of Birth");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 169, 67, -1));
        getContentPane().add(ContactHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 203, 119, -1));

        jLabel5.setText("Contact");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 206, 67, -1));

        jLabel6.setText("Stream");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 243, 67, -1));

        jLabel7.setText("Semester");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 67, -1));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 405, 90, 34));

        jLabel8.setText("BloodGroup");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 309, 67, -1));
        getContentPane().add(BloodGroupHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 306, 122, -1));

        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 343, 67, -1));

        Addressholder.setColumns(20);
        Addressholder.setRows(5);
        jScrollPane1.setViewportView(Addressholder);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 343, -1, 83));

        jLabel10.setText("PASSWORD");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 70, 20));

        passwordHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordHolderActionPerformed(evt);
            }
        });
        getContentPane().add(passwordHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 130, -1));

        jButton2.setFont(new java.awt.Font("Viner Hand ITC", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 90, 30));

        StreamHolder.setText("Your Branch");
        getContentPane().add(StreamHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 120, 20));

        SemesterHolder.setText("Your Current Sem");
        getContentPane().add(SemesterHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 120, 20));

        Name.setText("yourUserName");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 100, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LastNameHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameHolderActionPerformed

    private void FirstnameHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameHolderActionPerformed

    private void passwordHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordHolderActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            StudentWork a=new StudentWork();
                                    a.setVisible(true);
                                    this.setVisible(false);  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        //Her
        /* Name.setText(rs.getString("username"));
                FirstnameHolder.setText(rs.getString("FirstName"));
                LastNameHolder.setText(rs.getString("LastName"));
                DOBHolder.setText(rs.getString("DOB"));
                ContactHolder.setText(rs.getString("contact"));
                StreamHolder.setText(rs.getString("stream"));
                SemesterHolder.setText(rs.getString("Semester"));
                BloodGroupHolder.setText(rs.getString("BloodGroup"));
                Addressholder.setText(rs.getString("address"));
                passwordHolder.setText(rs.getString("password"));*/
        String fetch_user;
        AdminPage a = new AdminPage();
        fetch_user = a.getUserNameofStudents();
        s.setUserName(fetch_user);
            s.setFirstName(FirstnameHolder.getText()); 
            s.setLastName(LastNameHolder.getText()); 
            s.setDob(DOBHolder.getText());
            s.setPassword(passwordHolder.getText());
            s.setAddress(Addressholder.getText());
            s.setStream(StreamHolder.getText());
            s.setBloodGroup(BloodGroupHolder.getText());
            s.setSemester(SemesterHolder.getText()); 
            s.setContact(ContactHolder.getText());
       
            String result=s.updateDetails();
            
            fetch_user=a.getUserNameofStudents();
            JOptionPane.showMessageDialog(this,result);
        
            
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStudentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Addressholder;
    private javax.swing.JTextField BloodGroupHolder;
    private javax.swing.JTextField ContactHolder;
    private javax.swing.JTextField DOBHolder;
    private javax.swing.JTextField FirstnameHolder;
    private javax.swing.JTextField LastNameHolder;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel SemesterHolder;
    private javax.swing.JLabel StreamHolder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField passwordHolder;
    // End of variables declaration//GEN-END:variables
}
